### ISSUE TITLE
Randomized ordering does not persist across pagination, leading to duplicate results returned

### ISSUE THREAD

**Issue by sparadiso** [CitrineInformatics/java-citrination-client#47]
Running a search with `randomResults(true)` does not paginate over a static list of hits - instead, the results are reordered with every new page and then the top `n` are returned. 

It would be nice to avoid data duplication by passing along a random seed with the query that ensures consistent ordering across pagination so that no duplicates are drawn.

**Comment by sparadiso** [comment]
cc: @kjaym @eantono

**Comment by kjaym** [comment]
We can do.

**Comment by kjaym** [comment]
Is live on stage. Please test and acknowledge if it works (if you set e.g. randomSeed(1) and run a query twice then you should get the same results).

**Comment by kjaym** [comment]
CC @sparadiso @eantono

**Comment by sparadiso** [comment]
will test first thing tomorrow - thanks for squeezing this in @kjaym. This will def make our lives easier.

**Comment by kjaym** [comment]
@sparadiso @eantono Something to keep in mind here. The order will only be predictable if the data in the query scope does not change. 

Say that you have a query with 100 records in its results set. You supply a random seed. You can paginate forward and backward to your heart's content and get the same results in the same order.

As soon as a different record set comes into scope, whether it is a replacement of an existing record or an addition/deletion, the random order will change. This means that the order could change in the middle of pagination and you could still get duplicates. There are in theory ways around this but require significantly more work.

**Comment by sparadiso** [comment]
@eantono tested and confirmed this works! Thanks @kjaym
